import { ArrowTopRightOnSquareIcon } from "@heroicons/react/24/solid";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  About,
  Contact,
  Experience,
  Header,
  Hero,
  Projects,
  Skills,
} from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div
      className={`${styles.container} snap-y snap-mandatory overflow-scroll z-0 overflow-x-hidden 
      scrollbar scrollbar-track-gray-400/20  scrollbar-thumb-red-500/80`}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section id="hero" className="snap-start">
          <Hero />
        </section>

        {/* About  */}
        <section id="about" className="snap-center">
          <About />
        </section>
        {/* Experience */}
        <section id="experience" className="snap-center">
          <Experience />
        </section>
        {/* Skills */}
        <section className="snap-center" id="skills">
          <Skills />
        </section>
        {/* Projects */}
        <section className="snap-center" id="projects">
          <Projects />
        </section>
        {/* Blogs */}
        <section className="snap-center" id="contact">
          <Contact />
        </section>
        <Link href="#hero">
          <div className="sticky bottom-10 w-full cursor-pointer">
            <div className="flex items-center justify-end">
              <img
                src="https://pbs.twimg.com/profile_images/1577564208837062656/3HOjsIom_400x400.jpg"
                alt="profile"
                className="h-10 w-10 rounded-full grayscale hover:grayscale-0"
                title="Go to top"
              />
            </div>
          </div>
        </Link>
      </main>

      <footer className={styles.footer}>
        <small className="text-gray-500">
          Built with ❤️ by Rishikesh Shinde
        </small>
      </footer>
    </div>
  );
};

export default Home;
