import type { NextPage } from "next";
import Head from "next/head";
import { About, BackgroundCircles, Header, Hero } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div
      className={`${styles.container} snap-y snap-mandatory overflow-scroll z-0`}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section id="hero" className="snap-start">
          <Hero />
        </section>

        {/* About  */}
        <section id="about" className="snap-center">
          <About />
        </section>
        {/* Experience */}

        {/* Skills */}

        {/* Projects */}

        {/* Blogs */}

        {/* Contact Me */}
      </main>

      <footer className={styles.footer}>
        <small className="text-gray-500">
          Built with ❤️ by Rishikesh Shinde
        </small>
      </footer>
    </div>
  );
};

export default Home;
